lib/cocina/models.rb
To resemble https://github.com/sul-dlss/dor-services-client/blob/master/lib/dor/services/client.rb#L16
=> Fix handling of version by Zeitworks.

cocina-models.gemspec
This makes that expectation official
=> Our code requires version 1.x of dry-types

.rubocop.yml, lib/cocina/models/dro.rb, spec/cocina/models/dro_spec.rb
If it's not provided don't set the property, othewise it will be in violation of the schema
=> Don't let embargoReleaseDate be nil

lib/cocina/models/collection.rb, spec/cocina/models/collection_spec.rb
Ref  https://github.com/sul-dlss/dor-services-client/issues/106
=> Add a collection model

lib/cocina/models/dro.rb, spec/cocina/models/dro_spec.rb
Ref  https://github.com/sul-dlss/dor-services-client/issues/106
=> Use the cocina DRO types

docs/cocina-base.jsonld
=> Add a jsonld vocabulary that we could dereference

lib/cocina/models/admin_policy.rb, lib/cocina/models/collection.rb, lib/cocina/models/dro.rb, lib/cocina/models/file.rb, lib/cocina/models/file_set.rb, lib/cocina/models/vocab.rb, spec/cocina/models/dro_spec.rb, spec/cocina/models/vocab_spec.rb
This will be helpful for assigning particular types of DROs
=> Extract a vocabulary class

docs/maps/DRO.json, docs/maps/Fileset.json, lib/cocina/models/dro.rb, lib/cocina/models/file_set.rb, spec/cocina/models/dro_spec.rb, spec/cocina/models/file_set_spec.rb
This matches what we're doing in sdr-api and is derivable from contentMetadata.xml
yes
=> Allow DRO to contain filesets

docs/maps/File.json
=> Make JSON valid

lib/cocina/models/file.rb, spec/cocina/models/file_spec.rb
need to know whether to shelve and preserve the object.
n/a
=> Add File administrative properties

docs/maps/DRO.json, docs/maps/ReleaseTag.json
Release tags were not documented.
yes
=> Add json schema about releaseTags

README.md, docs/README.md, docs/maps/Agent.json, docs/maps/Collection.json, docs/maps/DRO.json, docs/maps/File.json, docs/maps/Fileset.json, docs/maps/Sequence.json, docs/meta.json, docs/schema.json, docs/schema.md
Previously they did not have this recommended property.
yes
=> Generate documenation based on schemas

docs/maps/File.json, lib/cocina/models/file.rb, spec/cocina/models/file_spec.rb
Need to know if we should publish the file or not.
n/a
=> Add access controls to the File object

docs/maps/Collection.json, docs/maps/DRO.json, docs/maps/ReleaseTag.json, docs/schema.json, docs/schema.md
So the docs can be up to date.
yes
=> Regenerate documentation

.rubocop.yml, lib/cocina/models.rb, lib/cocina/models/admin_policy.rb, lib/cocina/models/catalog_link.rb, lib/cocina/models/collection.rb, lib/cocina/models/description.rb, lib/cocina/models/dro.rb, lib/cocina/models/file.rb, lib/cocina/models/file_set.rb, spec/cocina/models/collection_spec.rb, spec/cocina/models/dro_spec.rb
So we have a way to communicate about catkey.
n/a
=> Add a way to provide catkey

lib/cocina/models/admin_policy.rb, lib/cocina/models/admin_policy_builder.rb, lib/cocina/models/request_admin_policy.rb, spec/cocina/models/request_admin_policy_spec.rb
Need a way to request an AdminPolicy be create
n/a
=> Add a request to create an AdminPolicy

lib/cocina/models/admin_policy.rb, lib/cocina/models/admin_policy_attributes.rb, lib/cocina/models/collection.rb, lib/cocina/models/collection_attributes.rb, lib/cocina/models/description.rb, lib/cocina/models/dro.rb, lib/cocina/models/dro_attributes.rb, lib/cocina/models/file.rb, lib/cocina/models/file_attributes.rb, lib/cocina/models/file_set_attributes.rb, lib/cocina/models/release_tag.rb, spec/cocina/models/admin_policy_shared_examples.rb, spec/cocina/models/collection_shared_examples.rb, spec/cocina/models/description_spec.rb, spec/cocina/models/dro_shared_examples.rb, spec/cocina/models/file_set_shared_examples.rb, spec/cocina/models/file_shared_examples.rb, spec/cocina/models/file_spec.rb, spec/cocina/models/release_tag_spec.rb
=> Stop coercing strings to integer and boolean

lib/cocina/models/file.rb, spec/cocina/models/file_shared_examples.rb
Fixes #87 
Suddenly, after all this time, people realized sdrPreserve here should default to true.
na
=> file sdrPreserve default is true

lib/cocina/models/access.rb, lib/cocina/models/catalog_link.rb, lib/cocina/models/collection.rb, lib/cocina/models/dro.rb, lib/cocina/models/dro_structural.rb, lib/cocina/models/embargo.rb, lib/cocina/models/file.rb, lib/cocina/models/file_set.rb, lib/cocina/models/geographic.rb, lib/cocina/models/presentation.rb, lib/cocina/models/release_tag.rb, lib/cocina/models/sequence.rb, lib/cocina/models/title.rb, openapi.yml
You know, because descriptions are helpful.
No.
=> Descriptions

openapi.yml
=> Fix to openapi.yml.

spec/fixtures/description/etd.json, spec/fixtures/description/etd2.json
@arcadiafalcone provided updated examples.
No.
=> Update to etd examples

README.md
=> Added clarification about using this gem.

lib/cocina/models/access.rb, lib/cocina/models/dro_access.rb, openapi.yml
This will allow us to do registration using the cocina model.  Ref https://github.com/sul-dlss/dor-services-app/issues/773
no
=> Add the readLocation to Access and DROAccess

lib/cocina/models/request_dro.rb, lib/cocina/models/request_identification.rb, openapi.yml, spec/cocina/generator/schema_value_spec.rb, spec/cocina/models_spec.rb
This supports the requirements lined out in https://github.com/sul-dlss/dor-services-app/issues/852#issuecomment-626853346
=> Require sourceId when requesting a new DRO

lib/cocina/models/admin_policy_administrative.rb, lib/cocina/models/administrative.rb, lib/cocina/models/dro.rb, lib/cocina/models/request_collection.rb, lib/cocina/models/request_dro.rb, openapi.yml, spec/cocina/generator/schema_array_spec.rb, spec/cocina/generator/schema_ref_spec.rb, spec/cocina/generator/schema_spec.rb, spec/cocina/generator/schema_value_spec.rb, spec/cocina/models/validator_spec.rb, spec/cocina/models_spec.rb
=> All objects require an admin policy

openapi.yml
To provide additional description of source id.
NA
NA
=> Added documentation of sourceId to openapi.

.rubocop.yml, cocina-models.gemspec, lib/cocina/generator/generator.rb, lib/cocina/generator/schema_value.rb, lib/cocina/models.rb
Keep up to date with the latest in rubocop technology.
Test suite
n/a
=> Upgrade to latest version of rubocop

lib/cocina/generator/generator.rb
Fixes #132
Running the generator
n/a
=> Revert rubocop suggested change

lib/cocina/models/identification.rb, lib/cocina/models/request_dro.rb, lib/cocina/models/request_identification.rb, openapi.yml, spec/cocina/models_spec.rb
So that dor-services-app can apply a  default access from the admin policy
Fixes #131
Test suite.
openapi.yml
=> Allow requesting a DRO without providing access

lib/cocina/models/contributor.rb, lib/cocina/models/description.rb, lib/cocina/models/descriptive_access_metadata.rb, lib/cocina/models/descriptive_admin_metadata.rb, lib/cocina/models/descriptive_basic_value.rb, lib/cocina/models/descriptive_parallel_value.rb, lib/cocina/models/descriptive_structured_value.rb, lib/cocina/models/descriptive_value.rb, lib/cocina/models/descriptive_value_required.rb, lib/cocina/models/language.rb, lib/cocina/models/related_resource.rb, lib/cocina/models/source.rb, lib/cocina/models/standard.rb, lib/cocina/models/version.rb, openapi.yml, spec/cocina/generator/schema_array_spec.rb, spec/cocina/models/description_spec.rb, spec/fixtures/description/etd.json, spec/fixtures/description/etd2.json
Updates openapi spec to match COCINA description schema v4.
=> Description v4

docs/maps/DRO.json
=> add attribute to dro.json

lib/cocina/models/file.rb, lib/cocina/models/file_access.rb, lib/cocina/models/request_file.rb, openapi.yml
=> Add controlled digital lending access to files

README.md
We didn't yet have documentation for how to upgrade everything.
n/a
n/a
=> Add directions for releasing the gem

docs/maps/DRO.json, lib/cocina/generator/datatype.rb, lib/cocina/generator/generator.rb, lib/cocina/models/dro_structural.rb, lib/cocina/models/druid.rb, lib/cocina/models/request_dro_structural.rb, openapi.yml
See https://github.com/sul-dlss/argo/issues/2233
=> Add support for DROs belonging to multiple collections.

lib/cocina/models/identification.rb, lib/cocina/models/request_identification.rb, lib/cocina/models/source_id.rb, openapi.yml
So we don't have to write a in code validator in dor-services-app and we don't make invalid requests.
Test suite.
n/a
=> Validate the pattern of sourceId

openapi.yml
No functional changes
This makes it easier to diff with the openapi.yml in dor-services-app.
=> Alphabetize the subschemas

lib/cocina/models/description.rb, lib/cocina/models/title.rb, openapi.yml
This is easier to understand.  This change was signed off on by Arcadia.
=> Rename DescriptiveValueRequired to Title

openapi.yml
This will keep it in synch with https://github.com/sul-dlss/dor-services-app/pull/1073
Reverts #144
=> Rollback integer as valid value

openapi.yml
Explain why commented out data is present
n/a
n/a
=> Include context for commented type values

README.md
So the list reflects all dependent services.
Hard-earned experience.
README
=> Updated list of dependent services in README.

lib/cocina/models/description.rb, lib/cocina/models/descriptive_geographic_metadata.rb, openapi.yml
Unblocks sul-dlss/dor-services-app#1163
openapi validation - generated code.
N/A
=> Add DescriptiveGeographicMetadata to api spec

lib/cocina/models/classification.rb, lib/cocina/models/description.rb, openapi.yml
fixes a production issue and part of https://github.com/sul-dlss/dor-services-app/pull/1233
N/A
=> Remove unnecessary classification definition

lib/cocina/models/contributor.rb, lib/cocina/models/language.rb, lib/cocina/models/related_resource.rb, openapi.yml
Closes #187 
Online Swagger editor
cocina-descriptive-metadata
=> Add properties to relatedResource object

lib/cocina/models/contributor.rb, lib/cocina/models/related_resource.rb, openapi.yml
Per discussion, removing order until it is clear how this (or similar approach) could be round-tripped to MODS.
NA
openapi
=> Removes order.

lib/cocina/models/contributor.rb, lib/cocina/models/description.rb, lib/cocina/models/descriptive_basic_value.rb, lib/cocina/models/descriptive_value.rb, lib/cocina/models/language.rb, lib/cocina/models/related_resource.rb, lib/cocina/models/title.rb, openapi.yml
To address https://github.com/sul-dlss/dor-services-app/issues/1936
swagger.io
cocina-descriptive-metadata
=> Update descriptive model

lib/cocina/models/event.rb, openapi.yml
Improve MODS<>Cocina roundtripping
generator
none
=> Add property to Event for easier roundtripping

lib/cocina/models/event.rb, openapi.yml
Better originInfo mapping
CircleCI
n/a
=> Event update

README.md
One step closer to world peace ...
NA
README
=> Suggested usage conventions.

lib/cocina/models/descriptive_parallel_contributor.rb, openapi.yml
Closes #223 . Prerequisite for https://github.com/sul-dlss/dor-services-app/pull/2418.
swagger.io, CircleCI
n/a
=> Add parallelContributor property to Contributor model

lib/cocina/models/access.rb, lib/cocina/models/version.rb, openapi.yml
This supports the work of sul-dlss/argo#2404.
CI
OpenAPI config
=> Copy copyright property from DROAccess to Access (used by collections)

lib/cocina/models/access.rb, lib/cocina/models/admin_policy_administrative.rb, lib/cocina/models/admin_policy_default_access.rb, lib/cocina/models/dro_access.rb, lib/cocina/models/file_access.rb, lib/cocina/models/language.rb, lib/cocina/models/release_tag.rb, lib/cocina/models/sequence.rb, spec/cocina/generator/schema_value_spec.rb
=> Use the defaults even for non-required fields

README.md
Fixes #247
Increased clarity for the team
N/A
README
=> Expand cocina-models documentation to make release process clearer

README.md
Fixes misspelled word in README
n/a
README updated.
=> README Typo fix 

lib/cocina/models/lane_medical_barcode.rb, openapi.yml
To fix https://github.com/sul-dlss/dor-services-app/issues/2851
=> validate lane medical barcodes

README.md
=> Add hydra_etd to the list of apps to be updated.

lib/cocina/models/doi.rb, openapi.yml
=> Add the test DOI prefix to the accepted list

.circleci/config.yml, Gemfile
=> Switch to sul-dlss orb for circleci config.

.circleci/config.yml
Use the orb v2 with better handling of code climate error.
=> updated orb

docs/maps/Collection.json, docs/maps/DRO.json, lib/cocina/models/admin_policy_administrative.rb, lib/cocina/models/dro_structural.rb, lib/cocina/models/request_dro_structural.rb, openapi.yml, spec/cocina/generator/schema_ref_spec.rb, spec/cocina/generator/schema_spec.rb, spec/cocina/models/validator_spec.rb, spec/cocina/models_spec.rb
=> Move hasAgreement to AdminPolicy

lib/cocina/models/request_admin_policy.rb, lib/cocina/models/request_collection.rb, lib/cocina/models/request_description.rb, lib/cocina/models/request_dro.rb, openapi.yml, spec/cocina/generator/schema_array_spec.rb
closes #293
Data validation.
unit
openapi
=> Requires PURL for non-request descriptions.

lib/cocina/models/administrative.rb, openapi.yml
Ref https://github.com/sul-dlss/argo/pull/3150#issuecomment-1051346427
=> Allow project to be nulled out

lib/cocina/models/request_admin_policy.rb, lib/cocina/models/request_collection.rb, lib/cocina/models/request_dro.rb, openapi.yml, spec/cocina/generator/schema_value_spec.rb, spec/cocina/models_spec.rb
=> Ensure that Request* objects start with version 1

cocina-models.gemspec, lib/cocina/models/validator.rb
Keep up to date on dependencies and prevent unnecessary deprecation warnings.
Fixes #323
=> Update to openapi_parser 1.0

.rubocop.yml, lib/cocina/models/collection.rb, lib/cocina/models/dro.rb, openapi.yml, spec/cocina/models/dro_access_spec.rb, spec/cocina/models/file_access_spec.rb, spec/cocina/models/validator_spec.rb, spec/cocina/models_spec.rb
closes #322
Stricter validation.
=> Require description for DRO and Collection.

cocina-models.gemspec
=> Match openapi_parser deps to work with committee

lib/cocina/models/access.rb, lib/cocina/models/admin_policy_default_access.rb, lib/cocina/models/citation_only_access.rb, lib/cocina/models/controlled_digital_lending_access.rb, lib/cocina/models/dark_access.rb, lib/cocina/models/dro_access.rb, lib/cocina/models/embargo.rb, lib/cocina/models/file_access.rb, lib/cocina/models/location_based_access.rb, lib/cocina/models/location_based_download_access.rb, lib/cocina/models/stanford_access.rb, lib/cocina/models/world_access.rb, openapi.yml, spec/cocina/generator/schema_value_spec.rb, spec/cocina/models/dro_access_spec.rb, spec/cocina/models/file_access_spec.rb
=> Rename readLocation to location

lib/cocina/models/admin_policy_access_template.rb, lib/cocina/models/admin_policy_administrative.rb, openapi.yml, spec/cocina/generator/schema_spec.rb, spec/cocina/generator/schema_value_spec.rb, spec/cocina/models/validator_spec.rb, spec/cocina/models_spec.rb
=> Replace defaultAccess with accessTemplate

README.md, lib/cocina/generator/generator.rb, lib/cocina/generator/vocab.rb, lib/cocina/models/file_set_type.rb, lib/cocina/models/object_type.rb, spec/cocina/generator/generator_spec.rb, spec/cocina/generator/schema_ref_spec.rb, spec/cocina/generator/schema_spec.rb, spec/cocina/generator/schema_value_spec.rb, spec/cocina/models/dro_access_spec.rb, spec/cocina/models/file_access_spec.rb, spec/cocina/models/object_type_spec.rb, spec/cocina/models/validator_spec.rb
=> Restructure vocabularies into separate classes

lib/cocina/models/access.rb, lib/cocina/models/admin_policy_access_template.rb, lib/cocina/models/citation_only_access.rb, lib/cocina/models/collection_access.rb, lib/cocina/models/controlled_digital_lending_access.rb, lib/cocina/models/dark_access.rb, lib/cocina/models/dro_access.rb, lib/cocina/models/embargo.rb, lib/cocina/models/file_access.rb, lib/cocina/models/location_based_access.rb, lib/cocina/models/location_based_download_access.rb, lib/cocina/models/stanford_access.rb, lib/cocina/models/world_access.rb, openapi.yml, spec/cocina/generator/schema_value_spec.rb, spec/cocina/models/dro_access_spec.rb, spec/cocina/models/file_access_spec.rb, spec/cocina/models/validator_spec.rb
=> Rename access to view

lib/cocina/generator/vocab.rb, lib/cocina/models.rb, lib/cocina/models/file_set_type.rb, lib/cocina/models/license.rb, lib/cocina/models/object_type.rb, lib/cocina/models/vocabulary.rb, spec/cocina/models/license_spec.rb
This keeps us from having to repeat the namespace URIs, thus reducing errors. This increases the code coverage too.
=> Add a vocabulary class

lib/cocina/models/dro_rights_description_builder.rb, lib/cocina/models/rights_description_builder.rb, spec/cocina/models/dro_rights_description_builder_spec.rb, spec/cocina/models/rights_description_builder_spec.rb
Closes #311 
Unit tests added.
=> Add RightDescriptionBuilder, DroRightsDescriptionBuilder, and test coverage for both

.rubocop.yml
Because this is what we do to keep it from yelling at us.
CI
=> Add new cop to Rubocop config

README.md
=> Added GB warning to README.

lib/cocina/models/collection.rb, lib/cocina/models/collection_with_metadata.rb, lib/cocina/models/dro.rb, lib/cocina/models/dro_with_metadata.rb, lib/cocina/models/file_set.rb, openapi.yml, spec/cocina/models/dro_access_spec.rb, spec/cocina/models/file_access_spec.rb, spec/cocina/models/title_builder_spec.rb, spec/cocina/models/validator_spec.rb, spec/cocina/models_spec.rb
=> Requires additional attributes.

lib/cocina/models/identification.rb, openapi.yml, spec/cocina/generator/schema_value_spec.rb, spec/cocina/models/dro_access_spec.rb, spec/cocina/models/dro_rights_description_builder_spec.rb, spec/cocina/models/file_access_spec.rb, spec/cocina/models/title_builder_spec.rb, spec/cocina/models/validator_spec.rb, spec/cocina/models_spec.rb
=> Make sourceId required for DROs

lib/cocina/models/title_builder.rb, spec/cocina/models/title_builder_spec.rb
closes #381
So that tests in dor_indexing_app pass.
Unit, tested with this branch for dor_indexing_app and dor-services-app.
=> Fix nonsorting character handling.

description_types.yml, lib/cocina/models/validators/description_types_validator.rb, lib/cocina/models/validators/validator.rb, spec/cocina/models/validators/description_types_validator_spec.rb
To have valid data you have to validate it.
Unit
=> Description type validation

lib/cocina/models/access_role.rb, openapi.yml, spec/cocina/generator/schema_value_spec.rb
=> Prune unused roles

lib/cocina/models/validators/description_types_validator.rb, spec/cocina/models/validators/description_types_validator_spec.rb
closes #400
Otherwise, get erroneous validation errors.
Unit
=> Handle parallelContributor and parallelEvents.

description_types.yml, docs/description_types.md
=> Fix typo in form type

description_types.yml, docs/description_types.md
=> Add types from data sample analysis

description_types.yml, docs/description_types.md
=> Merge form note types into note types

description_types.yml, docs/description_types.md
Add missing types so tests will pass
=> Add description types

description_types.yml, docs/description_types.md
=> Desc date type

description_types.yml, docs/description_types.md
=> Add descriptive types for validation

description_types.yml, docs/description_types.md
=> Re-add subtitle descriptive type.

.rubocop.yml, lib/cocina/models/builders/name_title_group_builder.rb, lib/cocina/models/validators/associated_name_validator.rb, lib/cocina/models/validators/validator.rb, spec/cocina/models/builders/name_title_group_builder_spec.rb, spec/cocina/models/validators/associated_name_validator_spec.rb
closes #391
* More validation
* Code re-use
=> Add validation of associated names. 

README.md
=> Adds docs on testing validation changes.

description_types.yml
Remove descriptive types temporarily added for remediation.
=> Remove temporary types for remediation

docs/_config.yml, docs/description_types.md, lib/cocina/generator/generator.rb, lib/cocina/models/contributor.rb, lib/cocina/models/descriptive_basic_value.rb, lib/cocina/models/descriptive_parallel_contributor.rb, lib/cocina/models/descriptive_value.rb, lib/cocina/models/title.rb, openapi.yml
=> Redesign descriptive types documentation

description_types.yml
Add more descriptions to type validation
=> Enhancements to descriptive types

docs/description_types.md
=> Regenerate descriptive types documentation

.rubocop.yml
=> Remove cruft from rubocop config

lib/cocina/from_fedora/descriptive/name_builder.rb, spec/cocina/from_fedora/descriptive/subject_name_spec.rb, spec/cocina/from_fedora/descriptive_spec.rb, spec/cocina/mapping/descriptive/mods/name_spec.rb, spec/cocina/mapping/descriptive/mods/related_item_spec.rb, spec/cocina/mapping/descriptive/mods/title_info_spec.rb
Keep cocina models in sync with https://github.com/sul-dlss/dor-services-app/pull/3930
=> Implemented uniform title with parallel name.

lib/cocina/models/mapping/purl.rb
This is a little clearer about what happens.
Test suite
=> Use the default attribute when calling class_attribute

lib/cocina/models/mapping/from_mods/description.rb
=> Remove incorrect comment.

description_types.yml, docs/description_types.md
=> Add provenance to event types

lib/cocina/rspec/factories.rb
This commits allows downstream tests to use gem-provided factories to build request models, which was needed for sul-dlss/sdr-api#446
* CI
* Tested in sdr-api as part of work on the issue referenced above
* Pointed DSA at this branch and the suite passed
=> Add request versions of models to RSpec factories

README.md
=> Update directions for testing cocina model changes.

lib/cocina/models/validators/description_values_validator.rb, lib/cocina/models/validators/validator.rb, openapi.yml, spec/cocina/models/validators/description_values_validator_spec.rb
=> Adds validation of description values.

description_types.yml
=> Add identifier type

spec/cocina/models/mapping/descriptive/mods/name_spec.rb
=> Update mapping for multilingual name with affiliation

README.md
The list was out-of-date. This points to the most current list.
=> Remove list of dependent applications.

lib/cocina/models/mapping/to_mods/geographic.rb, spec/cocina/models/mapping/to_mods/geographic_spec.rb
closes #491
Publishing was failing when mapping to MODs.
Unit
=> Handle missing value when mapping geo to mods.

lib/cocina/models/mapping/to_mods/geographic.rb
=> Tweak to use match?

lib/cocina/models/mapping/from_mods/subject.rb, lib/cocina/models/mapping/to_mods/subject.rb, spec/cocina/models/mapping/descriptive/mods/subject_name_spec.rb
=> Add mapping for subject name with an identifier to/from MODS

README.md
This is what the box is called now.
=> Rename sdr-deploy to sdr-infra in README

lib/cocina/models/validators/date_time_validator.rb, spec/cocina/models/validators/date_time_validator_spec.rb
Reverts #516 and #517
Fixes #518
Test suite.
=> Revert temporary validation exceptions

lib/cocina/models/validators/date_time_validator.rb, spec/cocina/models/validators/date_time_validator_spec.rb
This will allow us to fix bad dates in the repository
ci
=> Add edtf exceptions

README.md
because I had trouble figuring out the env var settings, I tried to clarify
=> README: tweak info for sdr-infra env var setting

.rubocop.yml, spec/cocina/generator/schema_ref_spec.rb, spec/cocina/models/mapping/from_mods/description_spec.rb, spec/cocina/models/mapping/from_mods/geographic_spec.rb, spec/cocina/models/validators/associated_name_validator_spec.rb, spec/cocina/models/validators/dark_validator_spec.rb, spec/cocina/models/validators/description_types_validator_spec.rb, spec/cocina/models/validators/description_values_validator_spec.rb, spec/cocina/models/validators/open_api_validator_spec.rb, spec/cocina/models/validators/purl_validator_spec.rb, spec/cocina/models_spec.rb
=> appease rubocop overlords

README.md
I was in brain dead mode and felt a little muddled, so I tried to make it middle-of-the-night stupid proof for myself.
=> readme updates regarding cocina-models updates instructions.

lib/cocina/generator/generator.rb
This commit speeds up model generation notably by significantly reducing the number of times we have to run rubocop, which is now down to one time.
CI + repeated generation runs
=> Generate models en masse and run rubocop en masse

.rubocop.yml, lib/cocina/models/mapping/from_mods/subject_authority_codes.rb
to avoid seeing the dreaded warnings.
=> rubocop: add new cops, adjust to them

README.md
=> Clarify patch release process.

description_types.yml
=> Adds FOLIO type.

README.md
=> Add link to Cocina description docs.

openapi.yml
So we can document what this means.
n/a
=> Add a description about CitationOnlyAccess

lib/cocina/models/builders/title_builder.rb, spec/cocina/models/builders/title_builder_spec.rb
To support nuanced indexing of titles for Argo, per sul-dlss/dor_indexing_app/issues/1044
Closes #653
CI.  
This adds a method to be used by dor_indexing app, with a direct call to the cocina method.
=> add methods for extracting "main title" from cocina descriptive

lib/cocina/models/builders/title_builder.rb, spec/cocina/models/builders/title_builder_spec.rb
To support nuanced indexing of titles for Argo, per https://github.com/sul-dlss/dor_indexing_app/issues/1044
part of https://github.com/sul-dlss/cocina-models/issues/655
CI.
This adds a method to be used by dor_indexing app, with a direct call to the cocina method.
=> titleBuilder: additional_titles passes tests, a few more tweaks to .build method

lib/cocina/models/validators/validator.rb
Validation is better than no validation.
This validation was checked against all production items.
=> Enabled description types validator

README.md
=> Add dor_indexing to release instructions.

README.md
Tweaks based on recent experience.
=> deploy instructions

README.md
helpful nudge for future validation runners
n/a
=> README: suggest screen session for validate-cocina

lib/cocina/models/citation_only_access.rb, lib/cocina/models/release_tag.rb, openapi.yml
fixes #695
- nothing in prod, QA, or stage failed validation with this branch
=> require ReleaseTag "what" attribute

description_types.yml, docs/description_types.md
=> Add Bates range and filing number to identifier types

description_types.yml
=> Add ROR to description_types.yml for contributor.identifier.

docs/description_types.md
=> Regenerate description types docs.

lib/cocina/models/builders/title_builder.rb, spec/cocina/models/builders/title_builder_spec.rb
Resolves #790. Once merged, will need to do https://github.com/sul-dlss/dor-services-app/issues/5311 and then test indexing for Argo display. Argo should not need changes, although we will need sample data. 
Unit. 
=> Add partLabel to title for display.

lib/cocina/models/mapping/to_mods/description.rb, lib/cocina/models/mapping/to_mods/mods_writer.rb, spec/cocina/models/mapping/to_mods/description_spec.rb
Resolves #802. Pass catalog links to where needed.
=> Pass identification metadata to mods writer

description_types.yml, docs/description_types.md, lib/cocina/models/related_resource.rb
Supports https://github.com/sul-dlss/hungry-hungry-hippo/issues/1446
=> Adds further related resource types

README.md
Make updates roll out more smoothly.
=> Update README.md for purl-fetcher steps

description_types.yml, docs/description_types.md
=> Add a translation contributor name type
