- .travis.yml
- README.md
To have a single build instead of multiple builds. I also removed the travis-ci.org webhook and installed the codeclimate coverage webhook.
yes, the badge
> Point at TravisCI.com for badge and service

- docs/maps/File.json
Previously there was no mechanism to express whether a file should be shelved, presumably because "Stacks" was not part of the cocina archiecture.
n/a
> Add a way to express if a file should be shelved

- cocina-models.gemspec
Corrected `cocina-models.gemspec` homepage to the resolved URL.
n/a
> Updated spec with resolved URL

- lib/cocina/models/admin_policy.rb
- lib/cocina/models/checkable.rb
- lib/cocina/models/collection.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/file.rb
- lib/cocina/models/file_set.rb
- spec/cocina/models/admin_policy_spec.rb
- spec/cocina/models/collection_spec.rb
- spec/cocina/models/dro_spec.rb
- spec/cocina/models/file_set_spec.rb
- spec/cocina/models/file_spec.rb
Instead of requiring upstream code to have to care about the internal structure of the cocina-models gem, introduce a new common interface that all cocina models implement that allows them to be asked about what they are.
This allows code like this:
```ruby
obj = object_client.find
return unless obj.is_a?(Cocina::Models::DRO)
```
to change to:
```ruby
obj = object_client.find
return unless obj.dro? # or .collection? .admin_policy? .file? .file_set? etc.
```
no.
> Allow interrogation of model types

- lib/cocina/models/admin_policy.rb
- spec/cocina/models/admin_policy_spec.rb
To support default_object_rights and registration workflow via cocina, so we can retire some Fedora calls from common-accessioning.
n/a
> Add administrative properties to AdminPolicy

- lib/cocina/models/dro.rb
- spec/cocina/models/dro_spec.rb
Required for removing calls to Fedora from common-accessioning.
n/a
> Add a property for a DROs AdminPolicy

- docs/maps/Collection.json
- lib/cocina/models/collection.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/release_tag.rb
- spec/cocina/models/collection_spec.rb
- spec/cocina/models/dro_spec.rb
So that we can communicate about release tags on collections. This will allow us to remove Fedora calls in the release workflow.
n/a
> Collections should have release tags

- lib/cocina/models/collection.rb
- spec/cocina/models/collection_spec.rb
So that consumers are able to get the collection's apo.  
n/a
> Add apo to collections

- docs/maps/DRO.json
- lib/cocina/models/dro.rb
- spec/cocina/models/dro_spec.rb
we need to know the collection for a DRO
n/a
> DRO should display a collection it is a member of

- lib/cocina/models/collection.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/file.rb
- spec/cocina/models/collection_spec.rb
- spec/cocina/models/dro_spec.rb
Ensure releaseTags is always an array
This removes a bunch of warnings about using shared defaults.
n/a
> Ensure we aren't using any shared defaults

- lib/cocina/models/admin_policy.rb
- spec/cocina/models/admin_policy_spec.rb
Connects to sul-dlss/common-accessioning#556
To resolve https://github.com/sul-dlss/common-accessioning/issues/556 and allow future APOs to assert parent APOs.
no
> Allow admin policies to assert parent admin policies

- docs/maps/Collection.json
- docs/maps/DRO.json
- docs/maps/Description.json
- docs/maps/Title.json
- lib/cocina/models/admin_policy.rb
- lib/cocina/models/collection.rb
- lib/cocina/models/description.rb
- lib/cocina/models/dro.rb
- spec/cocina/models/admin_policy_spec.rb
- spec/cocina/models/collection_spec.rb
- spec/cocina/models/dro_spec.rb
- spec/cocina/models_spec.rb
So we can store descriptive metadata
n/a
> Add the beginnings of a descriptive metadata schema

- lib/cocina/models/dro.rb
- spec/cocina/models/dro_spec.rb
So we can provide a sourceId property.
n/a
> Items should have a source_id

- .rubocop.yml
- lib/cocina/models.rb
- lib/cocina/models/collection.rb
- lib/cocina/models/collection_builder.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/dro_builder.rb
- lib/cocina/models/request_collection.rb
- lib/cocina/models/request_dro.rb
- spec/cocina/models/request_collection_spec.rb
- spec/cocina/models/request_dro_spec.rb
So that we can model requests that don't have identifiers
n/a
> Create request models

- lib/cocina/models.rb
- spec/cocina/models_spec.rb
For building Request* objects
This pattern is used in dor-services-app and it is so similar to the build method, it seems it should be here.
n/a
> Add a build_request method

- lib/cocina/models/dro.rb
So that embargo is actually optional.
No.
> Makes embargo trully optional.

- lib/cocina/models/collection.rb
- lib/cocina/models/dro.rb
- spec/cocina/models/collection_spec.rb
- spec/cocina/models/dro_spec.rb
This is required for registering from argo as the form lets you provide access.
n/a
> Add the access property for items and collections

- lib/cocina/models/admin_policy.rb
- lib/cocina/models/collection.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/request_admin_policy.rb
- lib/cocina/models/request_collection.rb
- lib/cocina/models/request_dro.rb
Description should be omitted, not produce nil. Nil disagrees with openapi.yml.
No.
> Made description omittable, not nil.

- lib/cocina/models/request_dro.rb
- lib/cocina/models/request_file_set.rb
- spec/cocina/models/request_dro_spec.rb
This identifer will be assigned after registration, so shouldn't be required when doing a registration.
n/a
> Add a RequestFileSet which does not require an externalIdentifier

- lib/cocina/models/request_file.rb
- lib/cocina/models/request_file_set.rb
- spec/cocina/models/request_file_spec.rb
This is for requesting a new file. It is just like File, but without the required externalIdentifier
n/a
> Add a RequestFile model

- lib/cocina/models/file.rb
- spec/cocina/models/file_spec.rb
So that we can record a mime-type
n/a
> Add support for mime type

- lib/cocina/models/file.rb
- spec/cocina/models/file_spec.rb
'transcription' is something we have a real use case for. The previous values were just conjecture and are not used
n/a
> Add a proper use predicate

- docs/maps/DRO.json
- docs/schema.json
- docs/schema.md
- lib/cocina/models/dro.rb
- lib/cocina/models/request_dro.rb
- spec/cocina/models/dro_spec.rb
- spec/cocina/models/request_dro_spec.rb
This will support geographic objects (e.g. https://argo.stanford.edu/view/druid:bb033gt0615)
yes
> Add optional geo metadata

- lib/cocina/models/request_file_set.rb
- spec/cocina/models/request_file_set_spec.rb
Because RequestFiles don't need to have externalIdentifiers
n/a
> RequestFileSet contains RequestFiles

- lib/cocina/models/file.rb
- lib/cocina/models/request_file.rb
OCD.
We only NEED parens in these situations when there is ambiguity.  That is true for send line below due to curly braces, but NOT true for first line.
```ruby
attribute :version, Types::Coercible::Integer
attribute(:identification, Identification.default { Identification.new })
```
n/a
n/a
If so, please confirm:
> remove unnec parens

- docs/maps/Collection.json
- docs/maps/DRO.json
- docs/schema.json
- docs/schema.md
- lib/cocina/models/dro.rb
- spec/cocina/models/dro_spec.rb
- spec/cocina/models/request_dro_spec.rb
To support properties required by rightsMetadata
n/a
If so, please confirm:
> Add copyright and reuseAndReproductionStatement to DROs

- .rubocop.yml
- spec/cocina/models/file_shared_examples.rb
- spec/cocina/models/file_spec.rb
- spec/cocina/models/request_file_spec.rb
- Reduce duplication of test code
- Ensure File and RequestFile models stay in sync.
Part of #70
na
If so, please confirm:
> refactor file and request_file specs to use file_shared_examples

- lib/cocina/models/admin_policy.rb
- lib/cocina/models/admin_policy_attributes.rb
- spec/cocina/models/admin_policy_shared_examples.rb
- spec/cocina/models/admin_policy_spec.rb
- spec/cocina/models/request_admin_policy_spec.rb
-    Reduce duplication of test code
-    Ensure AdminPolicy and RequestAdminPolicy models stay in sync.
Part of #70  (akin to PR #75 for File and RequestFile models)
na
> refactor (request_)admin_policy specs to use admin_policy_shared_examples

- spec/cocina/models/file_shared_examples.rb
- spec/cocina/models/file_spec.rb
Tests for the subschemas defined in a Model should go with the model spec.
na
> file spec tests subschema type coercion in right place

- lib/cocina/models/description.rb
- lib/cocina/models/release_tag.rb
- spec/cocina/models/admin_policy_shared_examples.rb
- spec/cocina/models/description_spec.rb
- spec/cocina/models/release_tag_spec.rb
in https://github.com/sul-dlss/cocina-models/pull/76#discussion_r387955380, @justinlittman rightly questioned why I was testing that a string boolean value passed as a Description model attribute raised an error.  This PR:
- changes the Description model to have a coercible boolean value
- I can't see the point in making it more restrictive than the other boolean types in ReleaseTag and File.Adminstrative
- has specs specific to the files declaring the models with coercible boolean values
- just as we show the version attribute to be coercible from a string in checkable model tests
- removes the spec in admin_policy_shared_examples from PR #76 that started this whole mess.
na
> description and release_tag specs for string coerced to boolean

- docs/maps/DRO.json
- docs/schema.json
- docs/schema.md
- lib/cocina/models/dro.rb
- spec/cocina/models/dro_shared_examples.rb
This will overwrite the base useAndReproductionStatement when the embargo has elapsed
Ref https://github.com/sul-dlss/google-books/issues/398
n/a
> Add useAndReproductionStatement to embargos

- lib/cocina/models/request_file.rb
- spec/cocina/models/request_file_spec.rb
External identifier is used by SDR API.
No.
> Adds externalIdentifier as optional attribute of Request File.

- lib/cocina/models/dro.rb
- spec/cocina/models/dro_shared_examples.rb
refs https://github.com/sul-dlss/google-books/issues/415
Allow setting partOfProject (equivalent to a project tag).
No.
> Adds partOfProject to Dro.

- .rubocop.yml
- lib/cocina/generator/schema_value.rb
- spec/cocina/models/admin_policy_shared_examples.rb
Fixes warnings like this:
```
Layout/LineLength has the wrong namespace - should be Metrics
```
no
> Use the correct namespace for LineLength

- lib/cocina/models/request_dro.rb
- openapi.yml
- spec/cocina/models/dro_shared_examples.rb
- spec/cocina/models/dro_spec.rb
- spec/cocina/models/request_dro_spec.rb
This allows us to inherit the access from the admin policy object.
n/a
> Allow a RequestDRO to ommit access subschema

- exe/generator
- lib/cocina/generator.rb
- lib/cocina/models.rb
Having two zeitwerks configs was causing problems in SDR API. Only a single is necessary.
No.
> Removed problematic and duplicative Zeitwerks configuration.

- lib/cocina/models/event.rb
- openapi.yml
closes #98
To better validate objects by disallowing unexpected properties.
No
> Added additionalProperties:false to all objects in openapi.

- docs/maps/DRO.json
- lib/cocina/models/access.rb
- lib/cocina/models/dro_access.rb
- openapi.yml
This allows us to do registration using the cocina endpoint.  This requires us to be able to set a download access level.
Ref https://github.com/sul-dlss/dor-services-app/issues/772
no
> Add a field for download level access

- README.md
to fix the CI badge in the README
Fixes #114 
I checked the badge by looking at the branch in github and making sure clicking on the badge in the README worked.  (https://github.com/sul-dlss/cocina-models/tree/fix-cov-badge )
na
> fix CI badge in README

- lib/cocina/models/sequence.rb
- openapi.yml
so that we can model virtual objects as a Sequence
See https://argo.stanford.edu/view/druid:hj097bm8879 as an example of a virtual object
> Add members to Sequence 

- lib/cocina/models/file.rb
- openapi.yml
We need to depend on Files having a Filename, so we should enforce this with the model.
> File objects require a filename

- cocina-models.gemspec
Rake 13 is the latest version
test suite
n/a
> Bump rake to 13

- lib/cocina/models/contributor.rb
- lib/cocina/models/descriptive_basic_value.rb
- lib/cocina/models/descriptive_parallel_value.rb
- lib/cocina/models/descriptive_value.rb
- lib/cocina/models/descriptive_value_required.rb
- lib/cocina/models/event.rb
- lib/cocina/models/identification.rb
- lib/cocina/models/language.rb
- lib/cocina/models/related_resource.rb
- lib/cocina/models/request_identification.rb
- lib/cocina/models/source.rb
- lib/cocina/models/standard.rb
- openapi.yml
- spec/cocina/generator/schema_array_spec.rb
there are no longer any string arrays in the Description model
test suite
n/a
> Fixes for description v4 branch.

- .rubocop.yml
- cocina-models.gemspec
Rubocop was not tightly pinned, which triggered an update that caused an error.
> Upgrade rubocop

- openapi.yml
To allow integer value for nonsorting character count
Swagger editor validation
cocina_descriptive_metadata/description_v4.json updated to description_v4-1.json
> Allow integer data type in DescriptiveBasicValue

- lib/cocina/models/descriptive_basic_value.rb
- lib/cocina/models/descriptive_value.rb
- lib/cocina/models/descriptive_value_required.rb
- lib/cocina/models/language.rb
- openapi.yml
Add language property to DescriptiveBasicValue.
swagger.io
cocina_descriptive_metadata/description_cocina_schema_v4-2.json
> Add language property to DescriptiveBasicValue

- lib/cocina/models/descriptive_basic_value.rb
- lib/cocina/models/descriptive_value.rb
- lib/cocina/models/descriptive_value_required.rb
- lib/cocina/models/language.rb
- openapi.yml
To simplify modeling for the language property in the context of DescriptiveBasicValue
swagger.io
cocina_descriptive_metadata/description_cocina_schema_v4-2.json
> Simplify modeling for the language property in the context of DescriptiveBasicValue

- README.md
This was requested in the standup on 2020-09-09
> Add list of downstream services to update

- lib/cocina/models/descriptive_basic_value.rb
- lib/cocina/models/descriptive_value.rb
- lib/cocina/models/descriptive_value_language.rb
- lib/cocina/models/descriptive_value_required.rb
- lib/cocina/models/language.rb
- openapi.yml
The generator can't cope with allOf for an attribute
> Extract a DescriptiveValueLanguage schema

- lib/cocina/models/descriptive_basic_value.rb
- lib/cocina/models/descriptive_value.rb
- lib/cocina/models/descriptive_value_language.rb
- lib/cocina/models/descriptive_value_required.rb
- lib/cocina/models/language.rb
- openapi.yml
To make model compliant with design principles and add a missing required property
swagger.io
cocina-descriptive-metadata/description-cocina-schema_v4-3.json
> Update descriptive model

- lib/cocina/models/access.rb
- openapi.yml
The Access schema is used only by collections. DROs and Files have their own Access schema which supports download access
> Remove download access from Access schema

- openapi.yml
To add a "version" property to the Source and Standard models
Online validator
n/a
> Update description model

- lib/cocina/models/descriptive_value_language.rb
- lib/cocina/models/source.rb
- lib/cocina/models/standard.rb
To bring the Ruby models in alignment with the specification.
By running through generation, per the README.
None.
> Updated DVL, source, and standard models with version attribute

- .rubocop.yml
- lib/cocina/generator/generator.rb
Connects to #135 (an alternative approach)
To reduce spammy output when generating models but without giving up on Rubocop. 
Output now looks like:
```shell
$ exe/generator generate                                        
create  lib/cocina/models/access.rb                                                                                                             
run  rubocop -a lib/cocina/models/access.rb > /dev/null from "."                                                                             
create  lib/cocina/models/administrative.rb                                                                                                     
run  rubocop -a lib/cocina/models/administrative.rb > /dev/null from "." …
```
> Quiet rubocop output when generating models

- lib/cocina/models/descriptive_value_language.rb
- lib/cocina/models/language.rb
- lib/cocina/models/standard.rb
- openapi.yml
Previously it was not accepting script as a valid property. Possibly becase it was doing allOf with members that specified additionalProperties: false
Ref https://github.com/sul-dlss/dor-services-app/issues/1157
> Separate language to its own model

- lib/cocina/models/classification.rb
- lib/cocina/models/description.rb
- openapi.yml
Adds the classification structure to the cocina descriptive data model.
N/A
N/A
> Add Classification to cocina descriptive model

- lib/cocina/models/classification.rb
- lib/cocina/models/description.rb
- openapi.yml
fixes https://github.com/sul-dlss/dor-services-app/issues/1231 by replacing the individual properties with the required subject property.
Unit
N/A
> Update classification property to subject

- openapi.yml
I noticed the comment was incorrect copypasta.
it's just the description in the openapi.yml
> openapi.yml: fix description of language status property

- lib/cocina/models/message_digest.rb
- openapi.yml
Previously it indicated Base64 encoding, but we always use hex encoding
> Fix the description for message digest

- openapi.yml
…r values to Contributor and RelatedResource
To get around bug preventing status from having both string and integer values, and to support H2 descriptive metadata mapping.
Online swagger.io validator
cocina-descriptive-metadata JSON schemas
> Make Description status string-only and add order property for integer values

- openapi.yml
Correcting some description text (effectively, a typo)
> openapi.yml: remove vestigial desc phrase

- .github/pull_request_template.md
Because I forgot to do this, and I may not be the only one.
> pr-template gets note about generating models for openapi.yml changes

- lib/cocina/models/descriptive_access_metadata.rb
**NOTE:  Changes to openapi.yml require generating models - see README.**
PR #191 was merged without model generation.  D'oh.   It is one small additive change that only affects cocina mappings, so I'm generating the updated models now.
I need this for mapping ticket sul-dlss/dor-services-app/issues/1499
> generate models: DescriptiveAccessMetadata gets digitalLocation

- .github/pull_request_template.md
**NOTE:  Changes to openapi.yml require generating models - see README.**
For the clueless among us, having the pr template ALSO say that we need to update openapi.yml in other apps is helpful.
> pr-template gets note about propagating openapi.yml changes

- README.md
Because communication is an important step when changing the API.
> Add note about communicating changes

- README.md
So keep list of dependent services accurate.
NA
> Add dor indexing app to list of dependent services.

- openapi.yml
Similar to problem encountered with DescriptiveBasicValue, DescriptiveValue incorrectly validates when additionProperties is set to false. This is causing a problem with mappings in dor-services-app.
NA
openapi
> Fix openApi for DescriptiveValue.

- openapi.yml
Creating a note with an appliesTo attribute was creating an error (in dor-services-app).
Linked to branch in dor-services-app and tested.
openapi
> Fix so that note can have an appliesTo attribute.

- lib/cocina/models/collection_identification.rb
- openapi.yml
This makes it possible to do asynchronous deposits, as the depositor needs to provide a sourceId and then listen for an object to come over the 'deposited' channel that has that sourceId. Then they will be able to know what the druid is for that object.  This is relevant to letting H2 use RabbitMQ for doing deposits.
> Add sourceId to collections

- lib/cocina/models/admin_policy_administrative.rb
- openapi.yml
Here is an example of one that does: https://argo.stanford.edu/view/druid:nz660xv7125
> Allow admin policies to have multiple registration workflows

- lib/cocina/models/access_role.rb
- lib/cocina/models/access_role_member.rb
- lib/cocina/models/admin_policy_administrative.rb
- openapi.yml
To support decoupling Argo/dor_indexing_app from Fedora
> Add access roles to AdminSetAdministrative

- lib/cocina/models/descriptive_parallel_event.rb
- openapi.yml
- I have branches with openapi.yml updated for both dor-services-app and sdr-api;  waiting for this the PR to be updated and for the gem release to move those forward.
- I will coordinate with FR and JCoyne re: updating dor-services-client and sdr-client gems, and the remaining PRs.  
- I believe the changes from THIS PR would only require updates to dor-services-app, as all the event handling is being done there.  🤷‍♀️ 
- I believe there are other changes since last gem release having to do with H2, which @jcoyne knows about.
Event modeling changes to enable MODS originInfo mapping that will roundtrip cleanly.
This is a redo of Arcadia's PR #210, but rebased …
> Update openapi.yml for Event mapping use cases

- lib/cocina/models/validator.rb
- spec/cocina/models/validator_spec.rb
closes #217
To allow the following when a DateTime is involved:
1. Convert a model to hash.
2. Edit the hash.
3. Create a model from the hash.
Unit
NA
> Allow validation to handle model that includes DateTime.

- lib/cocina/models/descriptive_parallel_event.rb
- lib/cocina/models/event.rb
- openapi.yml
- Add missing valueLanguage
- move Title to the correct place alphabetically in openapi.yml
CircleCI
n/a
> Fix valueLanguage in event models

- lib/cocina/models/access_role.rb
- openapi.yml
Supports missing types: https://app.honeybadger.io/projects/52894/faults/63360431
> Add missing AccessRole types

- lib/cocina/models/file_administrative.rb
- lib/cocina/models/version.rb
- openapi.yml
Fixes sul-dlss/dor-services-app#2407
Because it is independent from the rights metadata, thus should not be derived therefrom.
Will be tested in QA.
OpenAPI.
> Add publish attribute to file administrative metadata

- lib/cocina/generator/vocab.rb
- lib/cocina/models/file_set.rb
- lib/cocina/models/request_file_set.rb
- lib/cocina/models/vocab.rb
- openapi.yml
- spec/cocina/generator/schema_value_spec.rb
Some of the resource types currently in use overlap with the content types, so I made a separate namespace for these.
Fixes #226
> Add resource types to the model

- lib/cocina/generator/generator.rb
Without the require I get:
```
Traceback (most recent call last):
6: from exe/generator:9:in `<main>'
5: from /Users/amcollie/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
4: from /Users/amcollie/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
3: from /Users/amcollie/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
2: from /Users/amcollie/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
1: from /Users/amcollie/github/sul-dlss/cocina-models/lib/cocina/generator/generator.rb:18:in …
```
> Latest version of ruby requires this require fileutils

- lib/cocina/models/descriptive_parallel_contributor.rb
This is the result of running
```
exe/generator generate
```
against main.
> Update generated model to catch missed change.

- lib/cocina/generator/schema.rb
- lib/cocina/models/admin_policy_administrative.rb
- openapi.yml
Because APOs reference agreements.
> Add referenceAgreement to AdminPolicyAdministrative

- lib/cocina/models/access.rb
- lib/cocina/models/dro_access.rb
- openapi.yml
Ref #236
This is a missing property from the cocina-model that is in the access metadata.
> Add the license to the access metadata

- lib/cocina/models/identification.rb
- lib/cocina/models/request_identification.rb
- openapi.yml
It was mistakingly omitted when barcodes were added.
NA
NA
> Added barcode to request identification.

- lib/cocina/models/admin_policy_administrative.rb
- lib/cocina/models/admin_policy_default_access.rb
- openapi.yml
Currently we're just using an unvalidated chunk of XML to convey these values, but we should migrated to explicit values.
> Add properties for modeling the admin policy defaults

- lib/cocina/models/admin_policy_administrative.rb
- openapi.yml
It was not set to the correct schema before.
> Use the correct schema for AdminPolicy defaultAccess

- lib/cocina/models/admin_policy_default_access.rb
- openapi.yml
Since embargo comes from embargoMetadata, it can never come from defaultObjectRights, which is where the rest of these properties originate.  So this property will never be used.
> remove AdminPolicyDefaultAccess#embargo

- lib/cocina/models/collection_access.rb
- lib/cocina/models/dro_access.rb
- openapi.yml
So that it can be cleared out if it is not desired
> Allow copyright statement to be nullable

- openapi.yml
- spec/cocina/models/description_spec.rb
closes #265
Enforce canonical PURLs.
Unit
openapi.yml
> Validate that PURL starts with http, not https.

- openapi.yml
to silence some warnings from running `openapi-enforcer validate openapi.yml`
I will put in separate PRs for sdr-api and dor-services-app `openapi.yml` files.
unit tests, openapi.yml validation still works.
> openapi.yml: tweaks to silence validator warnings

- lib/cocina/models/admin_policy.rb
- lib/cocina/models/collection.rb
- lib/cocina/models/collection_identification.rb
- lib/cocina/models/description.rb
- lib/cocina/models/doi.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/identification.rb
- lib/cocina/models/purl.rb
- lib/cocina/models/related_resource.rb
- lib/cocina/models/request_admin_policy.rb
- lib/cocina/models/request_collection.rb
- lib/cocina/models/request_dro.rb
- lib/cocina/models/request_identification.rb
- openapi.yml
- spec/cocina/models_spec.rb
Fixes #269 
Needed so that h2 can transfer the object and it's associated DOI to DSA.
> Add a field for DOI in the Identification schema

- lib/cocina/models.rb
- spec/spec_helper.rb
otherwise, when an application eager loads (in production mode), we get this error:
```
Could not spawn process for application /opt/app/sdr/sdr-api/current: The application encountered the following error: expected file /opt/app/sdr/sdr-api/shared/bundle/ruby/2.6.0/gems/cocina-models-0.61.0/lib/cocina/models/doi.rb to define constant Cocina::Models::Doi, but didn’t (Zeitwerk::NameError)
```
> Add DOI to the zeitwerk inflector

- lib/cocina/models/doi.rb
- openapi.yml
- spec/cocina/models_spec.rb
This follows our existing dois: 10.25740/xd282zn6829 for example
> Adapt the DOI pattern to omit the druid namespace

- lib/cocina/models/request_identification.rb
- openapi.yml
- spec/cocina/models_spec.rb
Since we don't have a druid yet, we couldn't have a DOI for the item becuase we use the DRUID to mint the DOI
> Remove doi from request-identification

- docs/sampleETD/foxml.xml
- docs/sampleETD/xn109qc9773_bibframe.ttl
- docs/sampleETD/xn109qc9773_taco.json
- lib/cocina/models/purl.rb
- openapi.yml
- spec/cocina/models/description_spec.rb
- spec/fixtures/description/etd.json
- spec/fixtures/description/etd2.json
> Revert to using https for purl links

- README.md
Include information re: scripts now available to help with tasks for cocina-models release.
part of #176
> README: add information about using scripts to help with release steps

- lib/cocina/generator/schema_value.rb
- lib/cocina/models/admin_policy.rb
- lib/cocina/models/cocina_version.rb
- lib/cocina/models/collection.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/request_admin_policy.rb
- lib/cocina/models/request_collection.rb
- lib/cocina/models/request_dro.rb
- lib/cocina/models/validator.rb
- openapi.yml
- spec/cocina/generator/schema_value_spec.rb
- spec/cocina/models/validator_spec.rb
closes #285
To keep track of the cocina version of an object to allow for long-term maintenance.
Unit
openapi
> Adds cocinaVersion attribute.

- lib/cocina/models/validator.rb
> Fix cocina version check to take into account allOf and oneOf.

- lib/cocina/models/admin_policy_administrative.rb
- openapi.yml
> Removes referencesAgreement from administrative.

- lib/cocina/models/identification.rb
- lib/cocina/models/request_identification.rb
- openapi.yml
Ref: https://github.com/sul-dlss/argo/issues/3065
> Allow the barcode to be cleared out

- lib/cocina/models/identification.rb
- lib/cocina/models/request_identification.rb
- openapi.yml
- spec/cocina/models/validator_spec.rb
See https://github.com/OAI/OpenAPI-Specification/issues/1368 for why the earlier approach was unsuccessful
> Allow barcode to be nullable (really this time)

- lib/cocina/models/admin_policy_administrative.rb
- openapi.yml
This was previously deprecated in favor of defaultAccess
Fixes #307
> Remove defaultObjectRights

- lib/cocina/generator/generator.rb
- lib/cocina/generator/schema.rb
- lib/cocina/models/admin_policy.rb
- lib/cocina/models/collection.rb
- lib/cocina/models/description.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/request_admin_policy.rb
- lib/cocina/models/request_collection.rb
- lib/cocina/models/request_description.rb
- lib/cocina/models/request_dro.rb
- lib/cocina/models/validatable.rb
- spec/cocina/models/validator_spec.rb
closes #313
Catch validation problems faster.
Unit
> Validates on instantiation from existing instance.

- .rubocop.yml
- spec/cocina/generator/schema_array_spec.rb
- spec/cocina/models_spec.rb
When running `exe/generator` the output was flooded with:
```
Please also note that you can opt-in to new cops by default by adding this to your config:
AllCops:
NewCops: enable
RSpec/BeEq: # new in 2.9.0
Enabled: true
RSpec/BeNil: # new in 2.9.0
Enabled: true
```
This enables the new cops and auto corrects to apply.
> Enable new cops and auto-correct

- lib/cocina/models/request_administrative.rb
- lib/cocina/models/request_collection.rb
- lib/cocina/models/request_dro.rb
- openapi.yml
- spec/cocina/models/validator_spec.rb
This is only for routing messages, so we don't need to persist it in the model.
Ref https://github.com/sul-dlss/common-accessioning/issues/851
> Make partOfProject a request only parameter

- lib/cocina/models.rb
- spec/cocina/models_spec.rb
Resolves #346 and #318, to be more flexible with hash keys when building and raising clearer errors. 
Added specs and specs pass. 
> When building handle missing type or symbol keys

- lib/cocina/generator/generator.rb
- lib/cocina/generator/schema.rb
- lib/cocina/models.rb
- lib/cocina/models/admin_policy_with_metadata.rb
- lib/cocina/models/collection_with_metadata.rb
- lib/cocina/models/dro_with_metadata.rb
- lib/cocina/models/object_metadata.rb
- openapi.yml
- spec/cocina/generator/schema_spec.rb
Vocab-related files were being deleted when regenerating all files.
Local
> No delete vocab

- lib/cocina/generator/schema.rb
- lib/cocina/models.rb
- lib/cocina/models/admin_policy_with_metadata.rb
- lib/cocina/models/collection_with_metadata.rb
- lib/cocina/models/dro_with_metadata.rb
- lib/cocina/models/object_metadata.rb
- openapi.yml
- spec/cocina/generator/schema_spec.rb
refs https://github.com/sul-dlss/dor-services-app/issues/3568
To provide cocina classes that support metadata for locking and are compatible with DROs, Collections, and AdminPolicies.
> New schemas to support optimistic locking.

- .rubocop.yml
- README.md
- cocina-models.gemspec
- lib/cocina/models.rb
- lib/cocina/rspec.rb
- lib/cocina/rspec/matchers.rb
Fixes #319
This commit ports Cocina matchers from other codebases (argo, dor-services-app, sdr-client) so that they are available downstream. Companion PRs in these codebases are in progress and will be ready for review once we cut the next release of cocina-models.
CI, and this change was already tested successfully in argo, dor-services-app, and sdr-client.
> Add RSpec matchers for cocina comparisons

- lib/cocina/generator/generator.rb
Because we do not want the generate to delete Aaron's good work.
CI, and I ran the generator locally
> Do not clean description builders when generating

- lib/cocina/models.rb
- lib/cocina/models/version.rb
Else, zeitwerk attempts to load rspec matchers in the production environment, where rspec is not a dependency.
> Do not eager load rspec matchers and bump version to 0.69.2

- lib/cocina/generator/schema.rb
- lib/cocina/models.rb
- lib/cocina/models/admin_policy_with_metadata.rb
- lib/cocina/models/collection_with_metadata.rb
- lib/cocina/models/dro_with_metadata.rb
- lib/cocina/models/object_metadata.rb
- lib/cocina/rspec/matchers.rb
- openapi.yml
- spec/cocina/models_spec.rb
- spec/spec_helper.rb
This provides a mechanism for holding lock, create date, and modified date in a manner that is compatible with existing DRO, AdminPolicy, and Collection classes.
Unit, integration tests
> Optimistic locking

- .rubocop.yml
- cocina-models.gemspec
- lib/cocina/models/title_builder.rb
- spec/cocina/models/title_builder_spec.rb
This is required in dor-indexing-app for https://github.com/sul-dlss/dor_indexing_app/issues/796
Because it is used by the TopicBuilder here: https://github.com/sul-dlss/dor_indexing_app/blob/main/app/services/topic_builder.rb#L78
test suite
> Title builder should handle an array of Titles or DescriptiveValue

- README.md
To remind us all that running integration tests should be de rigeur when updating cocina-models for any but the most trival changes.
> README: add reminder to run integration tests after cocina-models changes

- README.md
agreement objects are a thing
README changes only.
> README: add a naming convention for DROs that are agreements.

- lib/cocina/models/vocabulary.rb
- spec/cocina/models/file_set_type_spec.rb
Argo often needs to get the URI by the short name, (e.g. from a spreadsheet upload).
> Add a hash accessor for properties

- lib/cocina/models/validators/catalog_links_validator.rb
- lib/cocina/models/validators/validator.rb
- spec/cocina/models/validators/catalog_links_validator_spec.rb
Fixes #379
To continue adding smarter semantic validation to cocina-models, and this is the next step. Having a single catalog link with the refresh property set to true makes it clear which catalog link ("catkey") to use for refreshing metadata.
CI
> Add validator ensuring no more than one refresh catalog link is present

- README.md
- docs/_config.yml
- docs/description_types.md
- lib/cocina/generator/generator.rb
- openapi.yml
Fixes #385
This commit adds the ability to generate user-facing documentation about how Cocina validates descriptive types. It is documented in the README and rendered by redoc via being linked to the OpenAPI specification.
CI
> Generate markdown from descriptive types

- description_types.yml
- docs/description_types.md
Add subject.structuredValue types found in data.
> Add missing subject.structuredValue types

- lib/cocina/models/validators/purl_validator.rb
- lib/cocina/models/validators/validator.rb
- spec/cocina/models/validators/purl_validator_spec.rb
closes #397
Valid data > invalid data
> Adds purl validation.

- lib/cocina/models/validatable.rb
- lib/cocina/models/validators/validator.rb
- spec/cocina/models/validators/validator_spec.rb
Mixed hashes were causing tests to valid in DSA.
Unit, DSA
> Handle mixed hashes when validating.

- description_types.yml
- spec/cocina/models/validators/description_types_validator_spec.rb
Fix descriptive_types.yml for a type with a special character.
Fixes #412
> fix description_types for identifier 'West Mat #'

- openapi.yml
from https://github.com/sul-dlss/dor-services-app/blob/106cd76eff236b7bb823629d68b4da01706d11e4/app/services/metadata_service.rb#L8
Ref https://github.com/sul-dlss/argo/issues/3512
> Add validation for catalog link

- lib/cocina/generator/schema_value.rb
- lib/cocina/models/access.rb
- lib/cocina/models/admin_policy_access_template.rb
- lib/cocina/models/citation_only_access.rb
- lib/cocina/models/controlled_digital_lending_access.rb
- lib/cocina/models/dark_access.rb
- lib/cocina/models/dro_access.rb
- lib/cocina/models/embargo.rb
- lib/cocina/models/file_access.rb
- lib/cocina/models/location_based_access.rb
- lib/cocina/models/location_based_download_access.rb
- lib/cocina/models/stanford_access.rb
- lib/cocina/models/world_access.rb
- openapi.yml
- spec/cocina/models/dro_access_spec.rb
Remove the need for special handling of stanford/none access.
Unit
> Do not require controlledDigitalLending for stanford/none.

- lib/cocina/models/mapping/from_mods/descriptive/hydrus_default_title_builder.rb
- lib/cocina/models/mapping/from_mods/descriptive/title_builder_strategy.rb
this should have been part of #441 but I missed it, and so did the specs.
> fix for refactor: use singular for FromMods::Title class name

- .rubocop.yml
- lib/cocina/rspec.rb
- lib/cocina/rspec/factories.rb
- spec/cocina/models/builders/dro_rights_description_builder_spec.rb
- spec/cocina/models/builders/rights_description_builder_spec.rb
- spec/cocina/models/builders/title_builder_spec.rb
- spec/cocina/models/dro_access_spec.rb
- spec/cocina/models/file_access_spec.rb
- spec/cocina/models_spec.rb
closes #445
So that all of the repos can share in factory goodness.
> Port cocina factory.

- lib/cocina/models/validators/dark_validator.rb
- spec/cocina/models/file_access_spec.rb
- spec/cocina/models/validators/dark_validator_spec.rb
The Dark Validator wasn't taking into account defaults. (That is: `DROAccess.new(view: 'dark') == DROAccess.new`).
Unit
> Handle access defaults in DarkValidator.

- spec/cocina/models/mapping/descriptive/h2/contributor_h2_spec.rb
Remove data mapped to MODS for roundtripping that is no longer needed.
> Remove unnecessary output from Cocina>MODS contributor mappings

- lib/cocina/models/mapping/to_mods/name_writer.rb
- spec/cocina/models/mapping/descriptive/h2/contributor_h2_spec.rb
- spec/support/mods_mapping_spec_helper.rb
closes #459
Remove mapping that is no longer necessary.
Unit
> Implement H2 contributor specs.

- lib/cocina/rspec/factories.rb
Fixes #454
Note: This commit will cause one spec in dor-services-app to fail but it ought to be easy to remediate once a cocina-models release goes out with this change included.
```
Failures:
1) CocinaMigrationService#migrate when migration needed maps and persists
Failure/Error: expect(ar_cocina_object.label).to eq('test object')
Expected "factory DRO label" to eq "test object".
/monkey_patches.rb:43:in `handle_failure'
7:in `block (2 levels) in <top (required)>'
Finished in 31.91 seconds (files took 3.57 seconds to load)
2088 examples, 1 failure, 5 pending
Failed examples:
rspec ./spec/services/cocina_migration_service_spec.rb:37 # CocinaMigrationService#migrate when migration needed maps and persists
```
CI + I pointed DSA at this branch (see above)
> Make factories easier to distinguish and identify

- lib/cocina/models.rb
Validation is redundant and has performance implications.
> Do not validate for with_metadata and without_metadata methods.

- lib/cocina/models/validators/associated_name_validator.rb
- lib/cocina/models/validators/description_types_validator.rb
- lib/cocina/models/validators/description_values_validator.rb
- lib/cocina/models/validators/validator.rb
- spec/cocina/models/validators/associated_name_validator_spec.rb
- spec/cocina/models/validators/description_types_validator_spec.rb
- spec/cocina/models/validators/description_values_validator_spec.rb
Improve performance by stopping redundant validation.
Before:
```
puts Benchmark.measure { Cocina::Models::Validators::Validator.validate(c.class, c) }
1.381309   0.008735   1.390044 (  1.393821)
```
After:
```
puts Benchmark.measure { Cocina::Models::Validators::Validator.validate(c.class, c) }
0.588038   0.007669   0.595707 (  0.596772)
```
> Validation performance improvements

- lib/cocina/models/mapping/to_mods/subject.rb
- spec/cocina/models/mapping/descriptive/mods/subject_name_spec.rb
> Retain role in name subject in Cocina>MODS direction

- openapi.yml
I noticed an error in the catkey barcode description.  I will port change and make PRs for sdr-api and dor-services-app but I am not going to generate models, nor put this in a new gem release.
> fix description of catkey barcode

- lib/cocina/models.rb
Hi! I just saw this configuration in passing.
You can ignore the very `lib/cocina/rspec` directory. This is simpler and more performant than a wildcard pattern.
> Simplify Zeitwerk configuration

- spec/cocina/models/mapping/descriptive/mods/subject_name_spec.rb
Missing pattern found in mapping
Implementation ticket #501 
> Add mapping for subject name with RWO identifier

- lib/cocina/models/validators/date_time_validator.rb
- lib/cocina/models/validators/validator.rb
- spec/cocina/models/validators/date_time_validator_spec.rb
Fixes #485
This commit turns on the date/time validator, which has been available for some time but has been waiting for date/time remediation to happen. This is now finished. As part of this work, pull the latest date/time regular expressions over from DSA, so that validation matches report behavior.
CI & tested against the full prod data set
* Two items failed validation and Arcadia remediated both.
> Turn on date/time validation

- lib/cocina/models.rb
- spec/cocina/models_spec.rb
This will enable H2 to decouple from druid-tools: https://github.com/sul-dlss/happy-heron/blob/dbf2991b058bb668e74c26b00d49d287ac920882/lib/tasks/deposit.rake#L45
ci
> Expose access to the druid regex

- lib/cocina/models/doi_exceptions.rb
- lib/cocina/models/doi_pattern.rb
- lib/cocina/models/identification.rb
- openapi.yml
Adds DOI exceptions (from H2 work) to the DOI schema.
Part of #512
rubular
> DOI schema gets exceptions for 5 hydrus identiiers

- .rubocop.yml
- spec/cocina/models/mapping/descriptive/mods/identifier_spec.rb
- spec/cocina/models/mapping/descriptive/mods/name_spec.rb
- spec/cocina/models/mapping/descriptive/mods/note_spec.rb
because I got sick of seeing warnings for the new cops when generating schemas.
changes are to rubocop.yml and 3 spec files;  CI build is sufficient
> appease rubocop overlords

- lib/cocina/models/validators/date_time_validator.rb
- spec/cocina/models/validators/date_time_validator_spec.rb
When the date is coded as w3cdtf and the format is MM/DD/YY allow it for now.  
We have bad data that doesn't work presently
ci
> Provide a temporary exemption for bad dates

- lib/cocina/models/validators/date_time_validator.rb
- spec/cocina/models/validators/date_time_validator_spec.rb
One digit dates are permitted to be invalid too. 🙄 
> Add exemption for one digit invalid dates

- lib/cocina/models/mapping/from_mods/part_builder.rb
I got excited when I learned about compact_blank in active support.
> use activesupport.compact_blank!

- lib/cocina/models/validators/date_time_validator.rb
- spec/cocina/models/validators/date_time_validator_spec.rb
edtf dates now all pass strict validation;  this PR removes the temporary allowance of some format violations.
Ran reports on edtf dates.
> edtf validation as it should be

- openapi.yml
It's important to have a low lie to truth ratio in the documentation. This documentation was contradicting the regex pattern
🤷
> Remove lies

- lib/cocina/models/description.rb
- lib/cocina/models/descriptive_parallel_contributor.rb
- lib/cocina/models/related_resource.rb
- lib/cocina/models/validators/description_types_validator.rb
- openapi.yml
- spec/cocina/models/validators/description_types_validator_spec.rb
Reverts sul-dlss/cocina-models#533
> Revert "remove unused, deprecated parallelContributor" due to EMPTY parallelContributor presence

- lib/cocina/models.rb
Part of https://github.com/sul-dlss/common-accessioning/issues/1005, which is timeouts on a large object.
Experimentation as shown in that ticket has demonstrated that for very large cocina objects (which in DSA are manipulated as in memory hashes), the detection of object type may not be very efficient due to the use of both the rails method `with_indifferent_access` (this makes a full copy of the giant hash in memory and returns a new object) and `fetch` (also possibly makes a copy of the hash based on console output).  Neither of these are really necessary, we can simply inspect the hash directly for the key and raise as needed.
While I did not characterize the actual performance/memory improvements achieved by this refactor (may only be a few seconds even for very large object), this …
> improve efficiency of object type detection

- lib/cocina/models/mapping/to_mods/subject.rb
- spec/cocina/models/mapping/to_mods/subject_spec.rb
Resolves #538 to handle different subject name identifier fields in mapping to MODS. 
Added a spec and ran unit tests.
> Change to subject identifier mapping to mods.

- lib/cocina/generator/datatype.rb
- lib/cocina/models/business_barcode.rb
- lib/cocina/models/catkey_barcode.rb
- lib/cocina/models/cocina_version.rb
- lib/cocina/models/description.rb
- lib/cocina/models/doi_exceptions.rb
- lib/cocina/models/doi_pattern.rb
- lib/cocina/models/druid.rb
- lib/cocina/models/lane_medical_barcode.rb
- lib/cocina/models/purl.rb
- lib/cocina/models/related_resource.rb
- lib/cocina/models/source_id.rb
- lib/cocina/models/standard_barcode.rb
Connects to #561
Because catalog record regexes are case-sensitive and, AFAICT, none of our current regexes should be case-insensitive.
CI and tested against all QA objects, all stage objects, and 1M prod objects on sdr-infra.
> Assume OpenAPI patterns are meant to be case-sensitive

- lib/cocina/generator/generator.rb
- lib/cocina/generator/schema.rb
- lib/cocina/generator/schema_array.rb
- lib/cocina/generator/schema_base.rb
- lib/cocina/generator/schema_value.rb
- lib/cocina/generator/union_type.rb
- lib/cocina/models/admin_policy.rb
- lib/cocina/models/admin_policy_administrative.rb
- lib/cocina/models/admin_policy_with_metadata.rb
- lib/cocina/models/administrative.rb
- lib/cocina/models/barcode.rb
- lib/cocina/models/catalog_link.rb
- lib/cocina/models/collection.rb
- lib/cocina/models/collection_identification.rb
- lib/cocina/models/collection_with_metadata.rb
- lib/cocina/models/description.rb
- lib/cocina/models/doi.rb
- lib/cocina/models/dro.rb
- lib/cocina/models/dro_with_metadata.rb
- lib/cocina/models/identification.rb
- lib/cocina/models/related_resource.rb
- lib/cocina/models/request_admin_policy.rb
- lib/cocina/models/request_administrative.rb
- lib/cocina/models/request_collection.rb
- lib/cocina/models/request_dro.rb
- lib/cocina/models/request_identification.rb
- spec/cocina/generator/generator_spec.rb
- spec/cocina/generator/schema_spec.rb
- spec/cocina/models/validators/open_api_validator_spec.rb
These commits change the Ruby models so that they are working more by reference and less by value, e.g., instead of having the druid regex in every model that has an `externalIdentifier`, point every `externalIdentifier` at the `Druid` model and let the model handle the validation.
Currently the models handle validation through a combination of validating against the OpenAPI spec and using the generated Ruby (dry-) types, and this commit adds a bit more smarts and descriptive oomph to the Ruby side.
A separate commit moves yet more smarts into the Ruby (dry-) types, allowing them to make use of union types defined in the OpenAPI spec, such as for barcodes and DOIs. This sets up a follow-on commit around Symphony and Folio catalog links which will similarly use union types.
CI & tested …
> Allow generators to create and use custom types and union types

- lib/cocina/generator/schema_base.rb
- lib/cocina/models/catalog_link.rb
- lib/cocina/models/created_in_folio_identifier.rb
- lib/cocina/models/folio_catalog_link.rb
- lib/cocina/models/migrated_from_symphony_identifier.rb
- lib/cocina/models/migrated_from_voyager_identifier.rb
- lib/cocina/models/symphony_catalog_link.rb
- openapi.yml
- spec/cocina/generator/schema_spec.rb
Connects to #561
Includes:
* Turn CatalogLink model into a union type
* Allows either Symphony-type catalog links ("catkeys" or "ckeys") or Folio-type catalog links ("HRIDs"). This split allows each type of catalog link to validate its own `catalog` string and `catalogRecordId` regex properties. 
* Discontinue allowing non-number characters in catkeys
* Tightens the regular expression governing what is a valid Symphony catalog record ID. Arcadia confirms this is the right value, and it is aligned with the regex for the new Folio catalog links (of the migrated-from-symphony variety). Additionally, I ran a report in DSA (https://github.com/sul-dlss/dor-services-app/pull/4357) confirming there are zero catkeys in QA, stage, and prod that contain non-number characters.
* Regenerate all …
> Add catalog links for Folio

- .rubocop.yml
- lib/cocina/generator/schema_base.rb
- lib/cocina/generator/schema_value.rb
- lib/cocina/models/collection_identification.rb
- lib/cocina/models/identification.rb
- lib/cocina/models/related_resource.rb
- lib/cocina/models/request_identification.rb
- spec/cocina/generator/schema_value_spec.rb
Custom types in Ruby models used to be "any" types, which allow null values. This change allows e.g. barcodes to be nulled out or reset. I discovered this deficiency in the models while rolling out cocina-models 0.87.0, and patched around it: https://github.com/sul-dlss/argo/blob/main/app/services/item_change_set_persister.rb#L134-L143. This cocina-models patch will allow the prior behavior of being able to reset these custom type values when the attribute is not required by adding logic around determining optionality.
> Allow non-required custom types to be optional

- lib/cocina/models/validators/catalog_links_validator.rb
- spec/cocina/models/validators/catalog_links_validator_spec.rb
closes #576
Allow folio and symphony to be marked for refresh.
Unit
> Adjust catalog links validator to take folio into account.

- .rubocop.yml
- lib/cocina/models.rb
- lib/cocina/models/mapping/normalizers/mods/subject_normalizer.rb
- spec/cocina/models_spec.rb
so that we can use `build()` on JSON that has metadata values
CI
> Expand Cocina::Models.build() to support metadata properties

- Gemfile.lock
- cocina-models.gemspec
Now that the latest Rubocop version no longer breaks the build, stop carrying the exclusion in the gemspec. Keep pace with dependencies.
CI
> Remove exclusion of latest Rubocop version

- Gemfile.lock
- cocina-models.gemspec
Update to latest to allow committee to be updated on gem consumers.
> Update openapi_parser to match latest committee

- lib/cocina/generator/generator.rb
- lib/cocina/generator/schema.rb
- lib/cocina/generator/schema_base.rb
- lib/cocina/models.rb
- lib/cocina/models/admin_policy_lite.rb
- lib/cocina/models/collection_lite.rb
- lib/cocina/models/dro_lite.rb
- lib/cocina/rspec/factories.rb
- spec/cocina/generator/generator_spec.rb
- spec/cocina/generator/schema_spec.rb
- spec/cocina/models_spec.rb
Allow for only partially populated cocina models.
> Adds support for lite (relaxed, unvalidated) models.

- lib/cocina/models/mapping/to_mods/form.rb
- lib/cocina/models/mapping/to_mods/subject.rb
~~NOTE:  Changes to openapi.yml require updating openapi.yml for sdr-api and dor-services-app and generating models - see README.~~
See PR #sul-dlss/dor_indexing_app/pull/993 which is failing because specs have nils where cocina-models doesn't expect them for xform to MODS.
It adds a safe navigator so our fragments of cocina in specs can be translated without error into MODS.
This accommodates dor_indexing_app using stanford-mods code for some Argo Solr index fields (so they are the same as SearchWorks index fields).   Part of #sul-dlss/dor_indexing_app/pull/992
specs.
> use safe navigator for temporal encoding code mapping, and 2 small refactors

- lib/cocina/models/mapping/to_mods/event.rb
dor_indexing_app was throwing errors due to conversion to MODS in cocina:
CI
> mods mapping: avoid nil on name.value

- lib/cocina/models/mapping/to_mods/event.rb
- spec/cocina/models/mapping/to_mods/description_spec.rb
- spec/cocina/models/mapping/to_mods/note_spec.rb
While working on https://github.com/sul-dlss/dor_indexing_app/issues/992 for resource_type - I discovered that while we follow the same logic internally to determine this should provide a resource_type of `Journal/Periodical`, when translating the cocina to mods in order to use `stanford-mods` to determine the resource_type we do not look for the parallelValue and thus miss `value="monthly"` and `type="frequency"`.
This checks if the note has a parallelValue and if so, uses value(s) found there to write the note.
The Cocina for a note that has a parallelValue:
```
#<Cocina::Models::DescriptiveValue 
structuredValue=[]
parallelValue=[
#<Cocina::Models::DescriptiveValue 
structuredValue=[] parallelValue=[] groupedValue=[] 
value="monthly" 
type="frequency" 
status=nil code=nil uri=nil …
```
> If an event note has a parallelValue, extract the data

- lib/cocina/models/validators/description_types_validator.rb
- lib/cocina/models/validators/validator.rb
- spec/cocina/models/validatable_spec.rb
- spec/cocina/models/validators/description_types_validator_spec.rb
- spec/cocina/models/validators/validator_spec.rb
Types validation was not being performed.
Unit, qa, stage, and prod.
> Fix description types validation

- lib/cocina/models/validators/validator.rb
- spec/cocina/models/validatable_spec.rb
There is existing data in production that fails validation with DescriptionTypesValidator. To prevent a problem, temporarily disabling the validator.
Unit
> Disable DescriptionTypesValidator

- docs/description_types.md
- lib/cocina/models/file.rb
- lib/cocina/models/request_file.rb
make the couple agreed upon touchups from https://github.com/sul-dlss/cocina-models/pull/640#issuecomment-1790929840
existing unit tests (`language_tag_validator_spec.rb` already confirms that `languageTag` can be omitted from `Cocina::Models::File` and `Cocina::Models::RequestFile` properties).
> touchups from file languageTag PR discussion

- lib/cocina/models/validators/dark_validator.rb
cribbed off this class for `LanguageTagValidator`, switched to something more concise for a similar method there, doing the same here
see https://github.com/sul-dlss/cocina-models/pull/643
(existing) unit tests
> make Cocina::Models::Validators::DarkValidator#invalid_files a bit more concise/idiomatic

- lib/cocina/models/file.rb
- lib/cocina/models/file_use.rb
- lib/cocina/models/language_tag.rb
- lib/cocina/models/request_file.rb
- openapi.yml
Prior to this commit, it was not possible to create a new instance of a `File` model containing use or language tag attrs with either or both removed (replaced by `nil`s). See https://github.com/sul-dlss/argo/blob/main/app/services/structure_updater.rb#L92, which prevents users from removing file use values. 
This commit makes it possible to do so.
Because this makes our models slightly more permissive, I don't think running a validation in a deployed env is worth the time/cost.
CI, `bundle console`
> Allow file use and language tag attrs to be removed

- lib/cocina/models/validators/description_values_validator.rb
- spec/cocina/models/validators/description_values_validator_spec.rb
This is draft while wrapping up styling/refactoring...
> Validate if values are whitespace only

- lib/cocina/models/validators/language_tag_validator.rb
- spec/cocina/models/validators/language_tag_validator_spec.rb
this makes `LanguageTagValidator` operate more like `DarkValidator`, which we determined in [slack discussion](https://stanfordlib.slack.com/archives/C09M7P91R/p1699289637148319) is likely desirable for real world validation usage:
@mjgiarlo 💬 
> What I think is happening: only some models use the ruby validation code (items, collections, APOs), and I don't think files are in that list. So they're strictly openapi validated.
>
> We likely need to rewrite the language tag validator so that it works against items instead of against files (so it runs at the item level and descends down into files, just like the dark-access validator)
> ...
> (and we can't lean on openapi validation for BCP unless we want to couple a given cocina-models release to a  an enum of allowed BCP values, which is …
> switch LanguageTagValidator to operate on DRO::TYPES so that it's invoked automatically when building item models

- lib/cocina/models/builders/title_builder.rb
- spec/cocina/models/builders/title_builder_spec.rb
To support nuanced indexing of titles for Argo, per https://github.com/sul-dlss/dor_indexing_app/issues/1044
part of #655
Go ahead, convince me that the previous reconstruction of title strings was better than the changes here.
CI.
This adds a method to be used by dor_indexing app, with a direct call to the cocina method.
> title_builder: add full_title method and fix .build results

- .rspec
- spec/spec_helper.rb
Randomizing specs is useful.
Longer format of output is useful when running a single file, but not when running all files - in my experience.
I've been running specs with these changes.
> update spec options

- lib/cocina/models/builders/title_builder.rb
- spec/cocina/models/builders/title_builder_spec.rb
On the way to better discovery in Argo (see sul-dlss/dor_indexing_app/issues/1044), I got more information from Arcadia on the correct way to implement title building (See #657).
This PR
- restores the reconstruction of structuredValue to _order of occurrence_
- for main_title and full_title, gets _BOTH_ parallel values (for equal weighting in search result ranking)
specs.  Will test upcoming gem release with integration tests.
> TitleBuilder corrections

- lib/cocina/models/builders/title_builder.rb
- spec/cocina/models/builders/title_builder_spec.rb
This addresses two problems surfaced by the commented out tests in the dor_indexing gem.  See sul-dlss/dor_indexing/pull/7 if you're curious, but I added the 2 failing tests from dor_indexing gem here.
specs.  I can update sul-dlss/dor_indexing/pull/7 if you want.
> TitleBuilder: fix two whitespace issues

- lib/cocina/models/builders/title_builder.rb
- spec/cocina/models/builders/title_builder_spec.rb
specs should live with the code;  I suspect TitleBuilder was moved from dor_indexing_app to cocina-models at some point and all the specs didn't come over with it.
I discovered these specs when I started to use the new "main_title" and "full_title" and "additional_titles" fields in dor_indexing gem.
CI.  Trivial code change;  it was just adding lots of specs.
> TitleBuilder gets detailed specs from dor_indexing gem

- lib/cocina/models/validators/description_values_validator.rb
- spec/cocina/models/validators/description_values_validator_spec.rb
Validator to address https://github.com/sul-dlss/argo/issues/4279. This goes down one level of nesting (`title.structuredValue`) and also validates one level of `relatedResource.title.structuredValue`. 
Unit. Ran `bin/validate-cocina` on QA, stage, and prod and there were no existing objects with this problem. 
> Validate for title.structuredValue.value having a type

- lib/cocina/models.rb
So we can build collections with metadata.
CI. It's only a typo fix.
> Fix typo in method that builds objects with metadata

- Gemfile.lock
- cocina-models.gemspec
- lib/cocina/models/validators/date_time_validator.rb
- lib/cocina/models/validators/w3cdtf_validator.rb
- spec/cocina/models/validators/w3cdtf_validator_spec.rb
Write our own (better) w3cdtf validator. Drop an unnecessary dependency.
> Remove depenency on RSS gem

- README.md
Update README to reflect a partial cocina models update process.
> update readme about partial cocina models updates

- README.md
Some more info about cutting new releases
> add additional info to README about validations

- lib/cocina/generator/generator.rb
Otherwise this file gets deleted.
> Don't delete utils.rb when re-generating

- .rubocop.yml
- lib/cocina/models/builders/name_title_group_builder.rb
- lib/cocina/models/mapping/from_mods/admin_metadata.rb
- lib/cocina/models/mapping/from_mods/event.rb
- lib/cocina/models/validatable.rb
Just a rubocop update to enable new cops and quiet the warnings/violations
> Enable new cops and update violations

- README.md
reminder to `bundle install` when bumping the gem version
i didn't forget to do it this time, but i have forgotten to do it in the past, so a reminder seemed nice 🙂 
> README: minor tweak to release instructions

- lib/cocina/models/validators/reserved_filename_validator.rb
- lib/cocina/models/validators/validator.rb
- spec/cocina/models/validators/reserved_filename_validator_spec.rb
closes #732
Prevent issues with Stacks file layout.
Unit
> Adds reserved name validator.

- Gemfile.lock
- cocina-models.gemspec
To reproduce and troubleshoot the error that caused us to pin commonmarker to 2.0.1, which is currently preventing upgrades to Ruby 3.4 (since commonmarker 2.0.2 is the version that adds Ruby 3.4 support).
CI
> Vary commonmarker pin depending on Ruby version

- Gemfile.lock
- cocina-models.gemspec
- lib/cocina/generator/generator.rb
- lib/cocina/generator/schema.rb
- lib/cocina/generator/schema_array.rb
- lib/cocina/generator/schema_base.rb
- lib/cocina/generator/vocab.rb
- lib/cocina/models.rb
Apparently we do not need it, and it is causing grief by way of commonmarker.
CI
> Drop Openapi3Parser dependency

- lib/cocina/models/mapping/from_mods/related_resource.rb
- lib/cocina/models/mapping/to_mods/related_resource.rb
- spec/cocina/models/mapping/descriptive/h2/related_item_h2_spec.rb
> Maps new H3 relatedResource types to MODS mapping.

- lib/cocina/models/folio_catalog_link.rb
- lib/cocina/models/validators/catalog_links_validator.rb
- openapi.yml
- spec/cocina/models/validators/catalog_links_validator_spec.rb
Resolves #785 to add digital serials fields to catalogLinks. Models were generated. 
Unit test added for validation.
> Add partLabel and sortKey to catalogLinks

- lib/cocina/models/builders/title_builder.rb
- spec/cocina/models/builders/title_builder_spec.rb
I had missed a few places in the TitleBuilder where we need to account for the presence of a `partLabel` and use that data in the display title and full title. 
We also need to continue to add part name and part number title parts to the display title and full title for indexing. I learned that there will be situations (post-migration) with a part name and part number that do not hold the 856 data. So we need to continue to add that info as well to the title (music and some less common scenarios).
This may cause some display duplication if anyone adds a partLabel before the migration. The migration will delete the part name and part number fields so things will be clean after that has occurred. 
Unit.
> Use partLabel and title parts if they are present

- lib/cocina/models/mapping/to_mods/title.rb
- spec/cocina/models/mapping/to_mods/title_spec.rb
> Pull part label from identification metadata instead of descriptive when mapping titles to MODS

- lib/cocina/models/mapping/to_mods/title.rb
- spec/cocina/models/mapping/to_mods/title_spec.rb
In order to improving debugging of indexing errors related to malformed titles, raise an error with the title_part structure for better honeybadger logging.
> Add additional context for logging to HB when title type is missing
